/** Multiple-choice questions on AI, ML and data science. `answer` is the index of the correct option. */

export interface QuizQuestion {
  id: string;
  topic: string;
  q: string;
  options: string[];
  answer: number;
  explain: string;
}

export const QUIZ: QuizQuestion[] = [
  { id: 'q-overfit', topic: 'Training', q: 'Training accuracy is 99% but test accuracy is 62%. What is most likely happening?', options: ['Underfitting', 'Overfitting', 'The learning rate is too small', 'The test set is too large'], answer: 1, explain: 'A big gap between training and test performance means the model memorised the training data instead of learning patterns that generalise.' },
  { id: 'q-lr-big', topic: 'Optimisation', q: 'The loss jumps around and grows instead of falling. What should you try first?', options: ['Increase the learning rate', 'Decrease the learning rate', 'Add more layers', 'Remove the bias terms'], answer: 1, explain: 'Steps that are too large overshoot the minimum again and again. A smaller learning rate usually calms training down.' },
  { id: 'q-relu', topic: 'Activations', q: 'What does ReLU return for an input of −3?', options: ['−3', '3', '0', '1'], answer: 2, explain: 'ReLU(z) = max(0, z), so every negative input becomes 0.' },
  { id: 'q-sigmoid-range', topic: 'Activations', q: 'What is the range of the sigmoid function?', options: ['(−1, 1)', '(0, 1)', '[0, ∞)', '(−∞, ∞)'], answer: 1, explain: 'σ(z) = 1 / (1 + e^−z) squashes any real number into the open interval (0, 1), so it can be read as a probability.' },
  { id: 'q-softmax', topic: 'Neural nets', q: 'The outputs of a softmax layer always…', options: ['are between −1 and 1', 'sum to 1', 'are integers', 'sum to 0'], answer: 1, explain: 'Softmax exponentiates the scores and divides by their total, giving a probability distribution that sums to 1.' },
  { id: 'q-gd', topic: 'Optimisation', q: 'Gradient descent moves the parameters…', options: ['in the direction of the gradient', 'against the gradient', 'at random', 'towards zero'], answer: 1, explain: 'The gradient points uphill (steepest increase of the loss), so we step the opposite way: θ ← θ − η∇L.' },
  { id: 'q-kmeans', topic: 'Classic ML', q: 'k-means is an example of…', options: ['supervised learning', 'unsupervised learning', 'reinforcement learning', 'a neural network'], answer: 1, explain: 'k-means groups points without any labels, so it is unsupervised.' },
  { id: 'q-knn-k', topic: 'Classic ML', q: 'In k-nearest neighbours, making k very large tends to…', options: ['make the boundary smoother (can underfit)', 'make the model memorise noise', 'speed up training a lot', 'have no effect'], answer: 0, explain: 'Voting over many neighbours averages away detail: the decision boundary gets smoother and can miss real structure.' },
  { id: 'q-precision', topic: 'Evaluation', q: 'A spam filter flags 10 emails; 8 really are spam. What is its precision?', options: ['0.2', '0.8', '10', 'Can’t tell without recall'], answer: 1, explain: 'Precision = true positives / everything flagged = 8 / 10 = 0.8.' },
  { id: 'q-recall', topic: 'Evaluation', q: 'There are 20 spam emails and the filter catches 15 of them. What is its recall?', options: ['0.25', '0.75', '0.15', '1.33'], answer: 1, explain: 'Recall = caught positives / all real positives = 15 / 20 = 0.75.' },
  { id: 'q-accuracy-trap', topic: 'Evaluation', q: '99% of transactions are legitimate. A model that always says “legitimate” has accuracy…', options: ['1%', '50%', '99%', 'undefined'], answer: 2, explain: 'It is right 99% of the time yet useless for catching fraud — why accuracy misleads on imbalanced data.' },
  { id: 'q-split', topic: 'Training', q: 'Why keep a separate test set?', options: ['To train faster', 'To estimate performance on unseen data', 'To tune the learning rate while training', 'To store extra labels'], answer: 1, explain: 'The test set is never used for training or tuning, so it gives an honest estimate of how the model does on new data.' },
  { id: 'q-validation', topic: 'Training', q: 'What is a validation set typically used for?', options: ['Final reporting only', 'Choosing hyperparameters', 'Replacing the training set', 'Data augmentation'], answer: 1, explain: 'We compare settings (learning rate, depth, k…) on validation data and keep the test set for the very end.' },
  { id: 'q-l2', topic: 'Training', q: 'L2 regularisation (weight decay) encourages…', options: ['larger weights', 'smaller weights', 'more layers', 'sparser data'], answer: 1, explain: 'It adds λ·Σw² to the loss, so large weights are penalised and the model stays simpler.' },
  { id: 'q-dropout', topic: 'Neural nets', q: 'Dropout randomly…', options: ['deletes training examples', 'turns off neurons during training', 'lowers the learning rate', 'shuffles the labels'], answer: 1, explain: 'Switching random neurons off forces the network not to rely on any single unit, which reduces overfitting.' },
  { id: 'q-epoch', topic: 'Training', q: 'One epoch means…', options: ['one weight update', 'one pass over the whole training set', 'one hour of training', 'one layer'], answer: 1, explain: 'An epoch is a full sweep through every training example (usually in many mini-batches).' },
  { id: 'q-batch', topic: 'Training', q: 'Compared with full-batch gradient descent, mini-batch SGD…', options: ['uses noisier but cheaper gradient estimates', 'always reaches a better minimum', 'needs no learning rate', 'uses only one parameter'], answer: 0, explain: 'Each mini-batch gives a rough estimate of the true gradient — much cheaper per step, and the noise can even help escape bad spots.' },
  { id: 'q-backprop', topic: 'Neural nets', q: 'Backpropagation is an efficient way to compute…', options: ['the loss', 'gradients of the loss with respect to every weight', 'the best architecture', 'the test accuracy'], answer: 1, explain: 'It applies the chain rule backwards through the network to get all the gradients in one pass.' },
  { id: 'q-vanish', topic: 'Neural nets', q: 'Why can deep networks with sigmoid activations learn slowly?', options: ['Sigmoid is too expensive', 'Its gradients are small, so they shrink layer after layer', 'It outputs negative numbers', 'It has no derivative'], answer: 1, explain: 'The sigmoid’s slope is at most 0.25; multiplying many of these in backprop makes gradients vanish.' },
  { id: 'q-linear-stack', topic: 'Neural nets', q: 'A network of 10 linear layers with no activation functions is equivalent to…', options: ['a single linear layer', 'a decision tree', 'a 10th-degree polynomial', 'a convolutional network'], answer: 0, explain: 'Composing linear maps gives another linear map. Non-linear activations are what give depth its power.' },
  { id: 'q-xor', topic: 'Neural nets', q: 'Why can’t a single neuron (a straight line) solve XOR?', options: ['XOR has too many points', 'XOR’s classes are not linearly separable', 'XOR needs a softmax', 'It can, with a big enough learning rate'], answer: 1, explain: 'No single straight line separates the XOR corners; a hidden layer is needed to bend the boundary.' },
  { id: 'q-cosine', topic: 'Embeddings', q: 'Cosine similarity of two vectors pointing in exactly opposite directions is…', options: ['1', '0', '−1', 'undefined'], answer: 2, explain: 'cos(180°) = −1. Same direction gives 1, perpendicular gives 0.' },
  { id: 'q-embed', topic: 'Embeddings', q: 'In a good word embedding, “king − man + woman” lands near…', options: ['prince', 'queen', 'man', 'crown'], answer: 1, explain: 'Differences between embeddings capture relationships, so the gender offset carries “king” over to “queen”.' },
  { id: 'q-token', topic: 'Language models', q: 'Large language models read text as…', options: ['whole sentences', 'tokens (word pieces)', 'individual bits', 'images of letters'], answer: 1, explain: 'Text is split into tokens — often word pieces from byte-pair encoding — and each token becomes a vector.' },
  { id: 'q-temp', topic: 'Language models', q: 'Raising the sampling temperature makes a language model’s output…', options: ['more predictable', 'more random / varied', 'shorter', 'always identical'], answer: 1, explain: 'Temperature divides the logits: higher values flatten the distribution so unlikely tokens get picked more often.' },
  { id: 'q-attention', topic: 'Language models', q: 'In attention, each token’s output is…', options: ['its own embedding unchanged', 'a weighted average of value vectors', 'the largest key', 'a random token'], answer: 1, explain: 'Queries are compared with keys to get weights (via softmax), which then mix the value vectors.' },
  { id: 'q-transformer', topic: 'Language models', q: 'Which architecture introduced in “Attention Is All You Need” powers most modern LLMs?', options: ['LSTM', 'Transformer', 'Random forest', 'Perceptron'], answer: 1, explain: 'The 2017 Transformer replaced recurrence with self-attention and now underlies GPT-style models.' },
  { id: 'q-q-learning', topic: 'Reinforcement learning', q: 'In Q-learning, Q(s, a) estimates…', options: ['the probability of state s', 'the expected future reward of taking action a in state s', 'the number of actions', 'the learning rate'], answer: 1, explain: 'Q is the long-run value of an action: the immediate reward plus the discounted value of what follows.' },
  { id: 'q-epsilon', topic: 'Reinforcement learning', q: 'In ε-greedy exploration with ε = 0.1, the agent…', options: ['always explores', 'explores 10% of the time and exploits otherwise', 'never explores', 'explores 90% of the time'], answer: 1, explain: 'With probability ε it tries a random action; otherwise it takes the best known one.' },
  { id: 'q-gamma', topic: 'Reinforcement learning', q: 'A discount factor γ close to 0 makes an agent…', options: ['far-sighted', 'short-sighted (cares about immediate reward)', 'random', 'stop learning'], answer: 1, explain: 'Future rewards are multiplied by γ each step, so a small γ makes later rewards nearly worthless.' },
  { id: 'q-mean-median', topic: 'Statistics', q: 'Salaries: 30k, 32k, 35k, 38k, 2,000k. Which summary is most robust to the outlier?', options: ['Mean', 'Median', 'Maximum', 'Sum'], answer: 1, explain: 'The median (35k) ignores how extreme the largest value is; the mean is dragged up to 427k.' },
  { id: 'q-std', topic: 'Statistics', q: 'If every value in a dataset is multiplied by 2, the standard deviation…', options: ['stays the same', 'doubles', 'quadruples', 'halves'], answer: 1, explain: 'Spread scales with the data. (The variance, being squared, quadruples.)' },
  { id: 'q-normal', topic: 'Statistics', q: 'About what fraction of a normal distribution lies within one standard deviation of the mean?', options: ['50%', '68%', '95%', '99.7%'], answer: 1, explain: 'The 68–95–99.7 rule: about 68% within 1σ, 95% within 2σ and 99.7% within 3σ.' },
  { id: 'q-clt', topic: 'Statistics', q: 'The Galton board’s bell curve is a demonstration of…', options: ['the central limit theorem', 'gradient descent', 'overfitting', 'Bayes’ theorem'], answer: 0, explain: 'Each marble’s position is a sum of many small left/right bounces, and sums of many random steps become normally distributed.' },
  { id: 'q-correlation', topic: 'Statistics', q: 'A correlation of −0.9 between two variables means…', options: ['no relationship', 'a strong relationship where one rises as the other falls', 'one causes the other', 'a weak positive relationship'], answer: 1, explain: 'Close to −1 means a strong negative linear relationship. Correlation alone never proves causation.' },
  { id: 'q-scaling', topic: 'Data', q: 'Why scale features (e.g. min-max) before k-NN?', options: ['To make the data smaller on disk', 'So one large-ranged feature doesn’t dominate distances', 'k-NN requires integers', 'It is never useful'], answer: 1, explain: 'Distances add up feature differences; a feature measured in thousands would drown out one measured in fractions.' },
  { id: 'q-onehot', topic: 'Data', q: 'One-hot encoding of the category “green” out of [red, green, blue] is…', options: ['[0, 1, 0]', '[1]', '[0, 0, 1]', '2'], answer: 0, explain: 'One position per category; only the matching category gets a 1.' },
  { id: 'q-tree', topic: 'Classic ML', q: 'A decision tree picks splits that…', options: ['maximise impurity', 'reduce impurity (e.g. Gini) the most', 'are random', 'use only the first feature'], answer: 1, explain: 'The best split makes the child groups as pure as possible, measured by Gini impurity or entropy.' },
  { id: 'q-linreg', topic: 'Classic ML', q: 'Linear regression usually minimises…', options: ['accuracy', 'mean squared error', 'cross-entropy', 'the number of features'], answer: 1, explain: 'Least squares: find the line that makes the average squared vertical distance to the points smallest.' },
  { id: 'q-logreg', topic: 'Classic ML', q: 'Despite its name, logistic regression is used for…', options: ['regression of prices', 'classification', 'clustering', 'dimensionality reduction'], answer: 1, explain: 'It passes a linear score through a sigmoid to predict the probability of a class.' },
  { id: 'q-crossent', topic: 'Neural nets', q: 'A classifier gives the correct class probability 0.01. Cross-entropy loss is…', options: ['small', 'large', 'zero', 'negative'], answer: 1, explain: 'Loss = −log(p). −log(0.01) ≈ 4.6, a big penalty for being confidently wrong.' },
  { id: 'q-conv', topic: 'Neural nets', q: 'Convolutional layers are especially good for images because they…', options: ['ignore neighbouring pixels', 'reuse the same small filter across the whole image', 'need no training', 'only work in black and white'], answer: 1, explain: 'Weight sharing lets one learned edge or texture detector work everywhere in the picture.' },
  { id: 'q-astar', topic: 'Search', q: 'A* search is guaranteed to find a shortest path when its heuristic…', options: ['overestimates the true cost', 'never overestimates the true cost', 'is random', 'is always zero only'], answer: 1, explain: 'An admissible heuristic (never an overestimate) keeps A* optimal; zero works too but turns it into Dijkstra.' },
  { id: 'q-boids', topic: 'Emergence', q: 'Boids flocking comes from three local rules: separation, alignment and…', options: ['gravity', 'cohesion', 'inheritance', 'backpropagation'], answer: 1, explain: 'Cohesion pulls each bird towards its neighbours’ centre; together with separation and alignment, flocks emerge.' },
];
